### ISSUE TITLE
Website front page is too generic

### ISSUE THREAD

**Issue by chiragnagpal** [autonlab/autonlab.github.io#2]
I appreciate all the hardwork that has gone into the website, but I think there are still issues that need to be fixed. 

I think the most fundamental issue is that the current front page doesn't introduce the lab at all. There is no way to figure out what the Auton Lab is, what kind of projects we are involved in and how or what relationship we have to Carnegie Mellon University. 

The front page should explicitly state that the Auton Lab is a academic research group, engaged in research in Machine Learning and Artficial Intelligence at Carnegie Mellon

**Comment by ngisolfi** [comment]
I agree with this point when it was written and I think we should continue discussing this thread.  Since then, we have application areas rotating.  Things I would like to see:

1) I think we still need better images
2) These could use text updates by Artur/Jeff/Barnabas
3) I would like to add Impact Areas to this carousel as well, so it is 4 application areas + ~6 impact areas in the carousel all together

Anything else come to mind?

**Comment by ngisolfi** [comment]
I'm messing around with changes to the page which i think will both solve this issue and be more readily mobile friendly.

<img width="912" alt="image" src="https://user-images.githubusercontent.com/9020201/185317245-a8916799-2d09-451e-b375-aaf7ae631ed6.png">

**Comment by chiragnagpal** [comment]
Looks much better now! Thanks for putting in all the work :) (the issue was raised about a year ago, we can close it now)
