### ISSUE TITLE
Image width on research page

### ISSUE THREAD

**Issue by ngisolfi** [autonlab/autonlab.github.io#34]
It looks like images on the research pages have incorrect aspect ratios.

I think we can solve this with an approach similar to the recent improvements on the applications page.

**Comment by betababb** [comment]
I have updated the research page to be formatted just like the applications page. I also added in a min-height of 130px because a few looked like they were a bit too short to be legible, and 130px seems like a sweet spot so none of the images look warped (particularly on mobile). Changes committed in 5c6c5e8.
